-- Immutable initial schema. Add new numbered migrations for subsequent changes.
CREATE TABLE IF NOT EXISTS `users` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `email` VARCHAR(255) NOT NULL, `name` VARCHAR(120) NOT NULL, `password_hash` VARCHAR(255) NOT NULL, `role` VARCHAR(20) NOT NULL, `verified` TINYINT(1) NOT NULL DEFAULT false, `demo_access` TINYINT(1) NOT NULL DEFAULT false, `token_version` INTEGER NOT NULL DEFAULT 0, `totp_secret` VARCHAR(512), `totp_pending` VARCHAR(512), `totp_counter` INTEGER NOT NULL DEFAULT -1, PRIMARY KEY (`id`), UNIQUE KEY `users_email` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sessions` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `user_id` VARCHAR(64) NOT NULL, `token_hash` VARCHAR(64) NOT NULL, `family` VARCHAR(64) NOT NULL, `expires_at` DATETIME NOT NULL, `revoked` TINYINT(1) NOT NULL DEFAULT false, `mfa` TINYINT(1) NOT NULL DEFAULT false, PRIMARY KEY (`id`), UNIQUE KEY `sessions_token_hash` (`token_hash`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `action_tokens` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `user_id` VARCHAR(64) NOT NULL, `token_hash` VARCHAR(64) NOT NULL, `kind` VARCHAR(20) NOT NULL, `expires_at` DATETIME NOT NULL, `consumed` TINYINT(1) NOT NULL DEFAULT false, PRIMARY KEY (`id`), UNIQUE KEY `action_tokens_token_hash` (`token_hash`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `courses` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `draft` JSON NOT NULL, `published_version_id` VARCHAR(64), `is_demo` TINYINT(1) NOT NULL DEFAULT true, `archived` TINYINT(1) NOT NULL DEFAULT false, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `course_versions` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `course_id` VARCHAR(64) NOT NULL, `number` INTEGER NOT NULL DEFAULT 1, `draft` JSON NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `course_versions_course_id_number` (`course_id`,`number`), FOREIGN KEY (`course_id`) REFERENCES `courses` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enrollments` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `user_id` VARCHAR(64) NOT NULL, `course_id` VARCHAR(64) NOT NULL, `version_id` VARCHAR(64) NOT NULL, `source` VARCHAR(20) NOT NULL, `completed_at` DATETIME, `certificate_id` VARCHAR(64), PRIMARY KEY (`id`), UNIQUE KEY `enrollments_user_id_course_id` (`user_id`,`course_id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT, FOREIGN KEY (`course_id`) REFERENCES `courses` (`id`) ON DELETE RESTRICT, FOREIGN KEY (`version_id`) REFERENCES `course_versions` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `free_picks` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `user_id` VARCHAR(64) NOT NULL, `level` VARCHAR(20) NOT NULL, `course_id` VARCHAR(64) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `free_picks_user_id_level` (`user_id`,`level`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT, FOREIGN KEY (`course_id`) REFERENCES `courses` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `progress` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `enrollment_id` VARCHAR(64) NOT NULL, `lesson_id` VARCHAR(64) NOT NULL, `position_seconds` INTEGER NOT NULL DEFAULT 0, `read` TINYINT(1) NOT NULL DEFAULT false, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `progress_enrollment_id_lesson_id` (`enrollment_id`,`lesson_id`), FOREIGN KEY (`enrollment_id`) REFERENCES `enrollments` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `credit_packs` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `name` VARCHAR(120) NOT NULL, `credits` INTEGER NOT NULL DEFAULT 0, `amount` INTEGER NOT NULL DEFAULT 0, `active` TINYINT(1) NOT NULL DEFAULT false, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `orders` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `user_id` VARCHAR(64) NOT NULL, `pack_id` VARCHAR(64) NOT NULL, `credits` INTEGER NOT NULL DEFAULT 0, `amount` INTEGER NOT NULL DEFAULT 0, `status` VARCHAR(32) NOT NULL, `stripe_session_id` VARCHAR(255), `payment_intent` VARCHAR(255), PRIMARY KEY (`id`), UNIQUE KEY `orders_stripe_session_id` (`stripe_session_id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT, FOREIGN KEY (`pack_id`) REFERENCES `credit_packs` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `credit_batches` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `user_id` VARCHAR(64) NOT NULL, `order_id` VARCHAR(64), `original` INTEGER NOT NULL DEFAULT 0, `remaining` INTEGER NOT NULL DEFAULT 0, `frozen` TINYINT(1) NOT NULL DEFAULT false, PRIMARY KEY (`id`), UNIQUE KEY `credit_batches_order_id` (`order_id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT, FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT, KEY `batches_fifo` (`user_id`,`frozen`,`created_at`), CHECK (`remaining` >= 0 AND `remaining` <= `original`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `credit_ledger` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `user_id` VARCHAR(64) NOT NULL, `batch_id` VARCHAR(64) NOT NULL, `delta` INTEGER NOT NULL DEFAULT 0, `kind` VARCHAR(32) NOT NULL, `reference_id` VARCHAR(64) NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT, FOREIGN KEY (`batch_id`) REFERENCES `credit_batches` (`id`) ON DELETE RESTRICT, KEY `ledger_user_date` (`user_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `refunds` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `order_id` VARCHAR(64) NOT NULL, `status` VARCHAR(32) NOT NULL, `stripe_refund_id` VARCHAR(255), `reason` VARCHAR(500) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `refunds_order_id` (`order_id`), FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payment_events` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `type` VARCHAR(80) NOT NULL, `object_id` VARCHAR(255) NOT NULL, `status` VARCHAR(32) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `attempts` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `enrollment_id` VARCHAR(64) NOT NULL, `score` INTEGER NOT NULL DEFAULT 0, `draft` JSON NOT NULL, `passed` TINYINT(1) NOT NULL DEFAULT false, PRIMARY KEY (`id`), FOREIGN KEY (`enrollment_id`) REFERENCES `enrollments` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `certificates` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `enrollment_id` VARCHAR(64) NOT NULL, `name` VARCHAR(120) NOT NULL, `title` VARCHAR(255) NOT NULL, `issuer` VARCHAR(255) NOT NULL, `completed_at` DATETIME NOT NULL, `draft` JSON NOT NULL, `revoked_at` DATETIME, `revoke_reason` VARCHAR(500), `supersedes_id` VARCHAR(64), `pdf_key` VARCHAR(255), PRIMARY KEY (`id`), FOREIGN KEY (`enrollment_id`) REFERENCES `enrollments` (`id`) ON DELETE RESTRICT, KEY `certificate_enrollment` (`enrollment_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `jobs` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `kind` VARCHAR(40) NOT NULL, `draft` JSON NOT NULL, `status` VARCHAR(20) NOT NULL, `attempts` INTEGER NOT NULL DEFAULT 0, `available_at` DATETIME NOT NULL, `locked_at` DATETIME, `lock_token` VARCHAR(64), `last_error` VARCHAR(255), PRIMARY KEY (`id`), KEY `jobs_claim` (`status`,`available_at`,`locked_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `audit_logs` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `actor_id` VARCHAR(64), `action` VARCHAR(80) NOT NULL, `target_id` VARCHAR(255) NOT NULL, `draft` JSON NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `review_cases` (`id` VARCHAR(64) NOT NULL , `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `order_id` VARCHAR(64), `kind` VARCHAR(50) NOT NULL, `status` VARCHAR(20) NOT NULL, `detail` VARCHAR(500) NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
